services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: web
    command: "gunicorn --bind 0.0.0.0:5000 manage:app"
    expose:
      - 5000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    container_name: db
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data_prod: